Algoritmo "EXERCICIO-65"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/09/2022
Var
// Seção de Declarações das variáveis 
   i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para i:=100 ate 0 passo -10 faca
        escreva(i)
   fimpara
   escreva(" Acabou!")

Fimalgoritmo